kind = "web"
previewPath = "/"
title = "المؤسسة الوطنية"
version = "1.0.0"
id = "artifacts/almossah"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20055

[services.development]
run = "pnpm --filter @workspace/almossah run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/almossah", "run", "build" ]
publicDir = "artifacts/almossah/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20055"
BASE_PATH = "/"
